import mongoose, { Schema, Document } from "mongoose";

export interface AdminSessionDoc extends Document {
  /** Unique per login — UUID generated by frontend */
  sessionId: string;
  /** Admin username */
  admin: string;
  /** Browser-generated device identifier (not Android deviceId) */
  deviceId: string;
  /** Raw User-Agent string */
  userAgent: string;
  /** Client IP address */
  ip: string;
  /** Parsed browser name (e.g. "Chrome 120") */
  browser: string;
  /** Parsed OS (e.g. "Windows 10", "Android 14", "iOS 17") */
  os: string;
  /** Last activity timestamp (epoch ms) */
  lastSeen: number;
  createdAt?: Date;
  updatedAt?: Date;
}

const AdminSessionSchema = new Schema<AdminSessionDoc>(
  {
    sessionId: { type: String, required: true, unique: true, index: true },
    admin: { type: String, required: true, index: true },
    deviceId: { type: String, required: true, index: true },
    userAgent: { type: String, default: "" },
    ip: { type: String, default: "" },
    browser: { type: String, default: "" },
    os: { type: String, default: "" },
    lastSeen: { type: Number, default: Date.now },
  },
  { timestamps: true },
);

// OLD index was: { admin: 1, deviceId: 1 } unique — caused merging
// NEW: sessionId is unique (1 row per login)
// Keep admin+deviceId as non-unique for fast queries
AdminSessionSchema.index({ admin: 1, deviceId: 1 });

export default mongoose.model<AdminSessionDoc>("AdminSession", AdminSessionSchema);
